# Name of your application. Used to uniquely configure containers.
# Name of your application. Used to uniquely configure containers.
service: force

# Name of the container image.
image: rbriski/force

# Deploy to these servers.
servers:
  - &host 143.244.178.63

require_destination: true

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: rbriski

  # Always use an access token rather than real password when possible.
  password:
    - DOCKER_REGISTRY_TOKEN
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!

builder:
  arch: amd64

proxy:
  healthcheck:
    path: /healthz
    interval: 20

env:
  clear:
    DB_HOST: *host
    AT_BASE_ID: appK55TripXu6J443
    AT_ROSTER: tblxFeLgJfC3OobXC
    AT_PARENTS: tblAelYcekjAKB7wg
    AT_EXPENSES: tblbmDRfIFweI3rih
    AT_PAYMENTS: tblLAiPaxvYyKZOry
    AT_EVENTS: tblEDzvuXiAOyvqvv
    PAYPAL_LINK: https://www.paypal.com/paypalme/Force2010G
    MIGRATION_SOURCE: file:///app/migrations
    MIGRATE_BIN: $HOME/go/bin/migrate
    POSTGRES_USER: postgres
  secret:
    - MAILGUN_API_KEY
    - SENDGRID_API_KEY
    - AT_API_KEY
    - POSTGRES_PASSWORD
    - SLACK_BOT_TOKEN
    - SLACK_APP_TOKEN
    - SLACK_SIGNING_SECRET

accessories:
  db:
    image: postgres:16-alpine
    host: *host
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql/data
